package net.sapodorado.eggmod.utils;

import net.minecraft.entity.EntityType;

public class EggModUtils {
    public static final EntityType<?>[] entities = {
        EntityType.BAT,
        EntityType.BEE,
        EntityType.BLAZE,
        EntityType.CAT,
        EntityType.CAVE_SPIDER,
        EntityType.CHICKEN,
        EntityType.COD,
        EntityType.COW,
        EntityType.CREEPER,
        EntityType.DOLPHIN,
        EntityType.DONKEY,
        EntityType.DROWNED,
        EntityType.ELDER_GUARDIAN,
        EntityType.ENDER_DRAGON,
        EntityType.ENDERMAN,
        EntityType.ENDERMITE,
        EntityType.EVOKER,
        EntityType.FOX,
        EntityType.GHAST,
        EntityType.GIANT,
        EntityType.GUARDIAN,
        EntityType.HOGLIN,
        EntityType.HORSE,
        EntityType.HUSK,
        EntityType.ILLUSIONER,
        EntityType.IRON_GOLEM,
        EntityType.LLAMA,
        EntityType.MAGMA_CUBE,
        EntityType.MULE,
        EntityType.MOOSHROOM,
        EntityType.OCELOT,
        EntityType.PANDA,
        EntityType.PARROT,
        EntityType.PHANTOM,
        EntityType.PIG,
        EntityType.PIGLIN,
        EntityType.PIGLIN_BRUTE,
        EntityType.PILLAGER,
        EntityType.POLAR_BEAR,
        EntityType.PUFFERFISH,
        EntityType.RABBIT,
        EntityType.RAVAGER,
        EntityType.SALMON,
        EntityType.SHEEP,
        EntityType.SHULKER,
        EntityType.SILVERFISH,
        EntityType.SKELETON,
        EntityType.SKELETON_HORSE,
        EntityType.SLIME,
        EntityType.SNOW_GOLEM,
        EntityType.SPIDER,
        EntityType.SQUID,
        EntityType.STRAY,
        EntityType.STRIDER,
        EntityType.TRADER_LLAMA,
        EntityType.TROPICAL_FISH,
        EntityType.TURTLE,
        EntityType.VEX,
        EntityType.VILLAGER,
        EntityType.VINDICATOR,
        EntityType.WANDERING_TRADER,
        EntityType.WITCH,
        EntityType.WITHER,
        EntityType.WITHER_SKELETON,
        EntityType.WOLF,
        EntityType.ZOGLIN,
        EntityType.ZOMBIE,
        EntityType.ZOMBIE_HORSE,
        EntityType.ZOMBIE_VILLAGER,
        EntityType.ZOMBIFIED_PIGLIN,
    };

    private EggModUtils() {
    }
}
